# Generated by Django 5.1.3 on 2024-11-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offerprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
