# Generated by Django 5.1.3 on 2024-11-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_products_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('PaperCraft', 'PaperCraft'), ('Wooden', 'Wooden'), ('Jute', 'Jute')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
