# Generated by Django 5.1.3 on 2024-12-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ShippingFee',
            field=models.CharField(default='Free', max_length=100),
        ),
    ]
