# Generated by Django 5.1.3 on 2024-12-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_products_created_at'),
    ]

    operations = [
    migrations.AlterField(
        model_name='products',
        name='created_at',
        field=models.DateTimeField(auto_now_add=True),
    ),
]

