# Generated by Django 5.1.3 on 2024-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_products_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
        migrations.AddField(
            model_name='products',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
