# Generated by Django 5.1.3 on 2024-12-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_products_created_at_products_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='datetime',
        ),
    ]
