# Generated by Django 5.1.3 on 2024-12-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_products_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
    ]
