# Generated by Django 5.1.3 on 2024-12-01 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_products_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('stock', models.IntegerField()),
                ('ShippingFee', models.CharField(default='Free', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('PaperCraft', 'PaperCraft'), ('Wooden', 'Wooden'), ('Jute', 'Jute')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.productss'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
