# Generated by Django 5.1.3 on 2024-12-05 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('OrderPlaced', 'OrderPlaced'), ('Shipped', 'Shipped'), ('OutForDelivery', 'OutForDelivery'), ('Delivered', 'Delivered'), ('cancelled', 'cancelled')], default='OrderPlaced', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.productss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
