# Generated by Django 5.1.3 on 2024-12-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_totals', to='account.cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_quantities', to='account.cart'),
        ),
    ]
