# Generated by Django 5.1.3 on 2024-12-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_deliveryaddress_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='product',
        ),
    ]
