# Generated by Django 5.1.3 on 2024-12-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_reviewreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewreply',
            old_name='message',
            new_name='reply_text',
        ),
    ]
